"""
Executor Agent Training for Agent0.
Trains the executor agent to solve tasks generated by the curriculum agent.

Paper Reference: Algorithm 1, Lines 11-24 (Executor Evolution)

Usage:
    uv run train_executor.py --curriculum_model_path ./outputs/curriculum/final_model
    uv run train_executor.py --help
"""

import os
import re
import sys
import argparse
import json
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any, Optional, Tuple

import torch
from datasets import Dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
from loguru import logger
from tqdm import tqdm

# Configure loguru for colorful output
logger.remove()
logger.add(
    sys.stderr,
    format="<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan> - <level>{message}</level>",
    level="INFO",
    colorize=True,
)
logger.add(
    "logs/train_executor_{time}.log",
    rotation="100 MB",
    level="DEBUG",
)

# Optional imports
try:
    import wandb
    WANDB_AVAILABLE = True
except ImportError:
    WANDB_AVAILABLE = False
    logger.warning("wandb not installed, W&B logging disabled")

try:
    from peft import LoraConfig, get_peft_model, TaskType
    PEFT_AVAILABLE = True
except ImportError:
    PEFT_AVAILABLE = False
    logger.warning("peft not installed, LoRA disabled")

# Local imports
from grpo import Agent0GRPOConfig, create_grpo_trainer
from self_consistency import (
    compute_p_hat,
    extract_boxed_answer,
    filter_frontier_tasks,
    save_generations_to_jsonl,
    save_generations_to_csv,
    normalize_answer,
)


# ============================================================================
# Model Loading
# ============================================================================

def load_model_and_tokenizer(
    model_name: str,
    use_lora: bool = False,
    lora_r: int = 32,
    device_map: str = "auto",
    torch_dtype: Optional[torch.dtype] = None,
) -> tuple:
    """Load model and tokenizer with optional LoRA."""
    logger.info(f"📦 Loading model: {model_name}")
    
    if torch_dtype is None:
        if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
            torch_dtype = torch.bfloat16
        else:
            torch_dtype = torch.float16
    
    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=True,
    )
    
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch_dtype,
        device_map=device_map,
        trust_remote_code=True,
    )
    
    if use_lora:
        if not PEFT_AVAILABLE:
            raise ImportError("peft not installed. Run: pip install peft")
        
        logger.info(f"🔧 Applying LoRA with r={lora_r}")
        lora_config = LoraConfig(
            task_type=TaskType.CAUSAL_LM,
            r=lora_r,
            lora_alpha=lora_r * 2,
            lora_dropout=0.05,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        )
        model = get_peft_model(model, lora_config)
        model.print_trainable_parameters()
    
    num_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    logger.success(f"✅ Model loaded: {num_params:,} total params, {trainable_params:,} trainable")
    
    return model, tokenizer


# ============================================================================
# Task Generation from Curriculum Agent
# ============================================================================

@torch.no_grad()
def generate_task_pool(
    curriculum_model,
    curriculum_tokenizer,
    num_tasks: int = 200,
    max_new_tokens: int = 2048,
    temperature: float = 1.0,
    system_prompt: Optional[str] = None,
) -> List[str]:
    """Generate a pool of tasks from the frozen curriculum agent."""
    if system_prompt is None:
        system_prompt = """You are an expert competition-math problem setter. Generate a challenging problem with:
<question> The full problem statement </question>
\\boxed{final answer}"""
    
    user_prompt = "Generate one new, challenging reasoning question now."
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    
    prompt_text = curriculum_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    
    tasks = []
    logger.info(f"📝 Generating {num_tasks} tasks from curriculum agent...")
    
    for i in tqdm(range(num_tasks), desc="Generating tasks", unit="task"):
        inputs = curriculum_tokenizer(prompt_text, return_tensors="pt").to(curriculum_model.device)
        
        outputs = curriculum_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            do_sample=True,
            top_p=0.99,
            pad_token_id=curriculum_tokenizer.pad_token_id,
        )
        
        task = curriculum_tokenizer.decode(
            outputs[0][inputs['input_ids'].shape[1]:],
            skip_special_tokens=True,
        )
        tasks.append(task)
    
    logger.success(f"✅ Generated {len(tasks)} tasks")
    return tasks


@torch.no_grad()
def sample_executor_responses(
    executor_model,
    executor_tokenizer,
    question: str,
    k: int = 4,
    max_new_tokens: int = 2048,
    temperature: float = 1.0,
) -> List[str]:
    """Sample k responses from executor for a given question."""
    messages = [
        {"role": "system", "content": "Solve the following problem step by step. Put your final answer in \\boxed{}."},
        {"role": "user", "content": question},
    ]
    
    prompt_text = executor_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = executor_tokenizer(prompt_text, return_tensors="pt").to(executor_model.device)
    
    responses = []
    for _ in range(k):
        outputs = executor_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            do_sample=True,
            top_p=0.99,
            pad_token_id=executor_tokenizer.pad_token_id,
        )
        
        response = executor_tokenizer.decode(
            outputs[0][inputs['input_ids'].shape[1]:],
            skip_special_tokens=True,
        )
        responses.append(response)
    
    return responses


# ============================================================================
# Dataset Curation (Algorithm 1, Lines 12)
# ============================================================================

def curate_frontier_dataset(
    tasks: List[str],
    executor_model,
    executor_tokenizer,
    k: int = 4,
    delta: float = 0.25,
    output_dir: Optional[str] = None,
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Curate frontier dataset by filtering tasks based on self-consistency."""
    logger.info(f"🔍 Curating frontier dataset from {len(tasks)} tasks...")
    logger.info(f"  Sampling k={k} responses per task")
    logger.info(f"  Frontier threshold δ={delta} (p̂ ∈ [{0.5-delta}, {0.5+delta}])")
    
    all_tasks_with_scores = []
    
    for idx, task in enumerate(tqdm(tasks, desc="Computing p̂ for tasks", unit="task")):
        question_match = re.search(r'<question>(.*?)</question>', task, re.DOTALL)
        if not question_match:
            continue
        
        question = question_match.group(1).strip()
        gt_answer = extract_boxed_answer(task)
        
        try:
            responses = sample_executor_responses(
                executor_model,
                executor_tokenizer,
                question,
                k=k,
            )
        except Exception as e:
            logger.error(f"Task {idx}: Failed to sample responses: {e}")
            continue
        
        p_hat, majority_answer, votes = compute_p_hat(responses)
        
        task_entry = {
            "task_idx": idx,
            "task": task,
            "question": question,
            "gt_answer": gt_answer,
            "p_hat": p_hat,
            "majority_answer": majority_answer,
            "vote_distribution": votes,
            "responses": responses,
        }
        all_tasks_with_scores.append(task_entry)
    
    # Filter frontier tasks
    frontier_tasks = filter_frontier_tasks(all_tasks_with_scores, delta=delta)
    
    logger.info(f"📊 Frontier filtering complete:")
    logger.info(f"  Total tasks processed: {len(all_tasks_with_scores)}")
    logger.info(f"  Frontier tasks retained: {len(frontier_tasks)}")
    logger.info(f"  Retention rate: {len(frontier_tasks)/max(len(all_tasks_with_scores), 1)*100:.1f}%")
    
    # Save logs if output_dir provided
    if output_dir:
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        all_tasks_path = output_dir / f"all_tasks_scored_{timestamp}.jsonl"
        save_generations_to_jsonl(all_tasks_with_scores, str(all_tasks_path), mode='w')
        
        frontier_path = output_dir / f"frontier_tasks_{timestamp}.jsonl"
        save_generations_to_jsonl(frontier_tasks, str(frontier_path), mode='w')
        
        summary_data = [
            {
                "task_idx": t["task_idx"],
                "p_hat": t["p_hat"],
                "majority_answer": t.get("majority_answer"),
                "gt_answer": t.get("gt_answer"),
                "is_frontier": abs(t["p_hat"] - 0.5) <= delta,
                "question_preview": t["question"][:100],
            }
            for t in all_tasks_with_scores
        ]
        csv_path = output_dir / f"task_summary_{timestamp}.csv"
        save_generations_to_csv(summary_data, str(csv_path), mode='w')
        
        logger.success(f"💾 Saved task logs to {output_dir}")
    
    return frontier_tasks, all_tasks_with_scores


def create_executor_training_dataset(
    frontier_tasks: List[Dict[str, Any]],
    tokenizer: AutoTokenizer,
) -> Dataset:
    """Create training dataset for executor from frontier tasks."""
    samples = []
    
    for task in tqdm(frontier_tasks, desc="Creating training dataset", unit="task"):
        question = task.get("question", "")
        majority_answer = task.get("majority_answer")
        p_hat = task.get("p_hat", 0.5)
        
        if not question or not majority_answer:
            continue
        
        messages = [
            {"role": "system", "content": "Solve the following problem step by step. Put your final answer in \\boxed{}."},
            {"role": "user", "content": question},
        ]
        
        prompt_str = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True,
        )
        
        samples.append({
            "prompt": prompt_str,
            "pseudo_label": majority_answer,
            "p_hat": p_hat,
            "task_idx": task.get("task_idx"),
        })
    
    logger.success(f"✅ Created executor training dataset with {len(samples)} samples")
    return Dataset.from_list(samples)


# ============================================================================
# Executor Reward Function
# ============================================================================

class ExecutorRewardComputer:
    """Computes executor reward based on answer correctness."""
    
    def __init__(
        self,
        output_dir: str = "./outputs",
        use_adpo_scaling: bool = False,
    ):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.use_adpo_scaling = use_adpo_scaling
        self.generation_log = []
        self.call_count = 0
        self.pseudo_labels = {}
        self.p_hats = {}
    
    def set_pseudo_labels(self, dataset: Dataset):
        """Set pseudo-labels from the training dataset."""
        for sample in dataset:
            prompt = sample["prompt"]
            self.pseudo_labels[prompt] = sample.get("pseudo_label")
            self.p_hats[prompt] = sample.get("p_hat", 0.5)
        logger.info(f"📋 Set {len(self.pseudo_labels)} pseudo-labels for reward computation")
    
    def __call__(
        self,
        prompts: List[str],
        completions: List[str],
        **kwargs
    ) -> List[float]:
        """Compute rewards for executor completions."""
        rewards = []
        self.call_count += 1
        
        pbar = tqdm(
            zip(prompts, completions),
            total=len(prompts),
            desc=f"Computing rewards (batch {self.call_count})",
            unit="sample",
            leave=False,
        )
        
        for idx, (prompt, completion) in enumerate(pbar):
            predicted_answer = extract_boxed_answer(completion)
            pseudo_label = self.pseudo_labels.get(prompt)
            p_hat = self.p_hats.get(prompt, 0.5)
            
            if predicted_answer is None or pseudo_label is None:
                reward = 0.0
                match = False
            else:
                pred_norm = normalize_answer(predicted_answer)
                label_norm = normalize_answer(pseudo_label)
                match = (pred_norm == label_norm)
                reward = 1.0 if match else 0.0
            
            if self.use_adpo_scaling:
                reward = reward * p_hat
            
            rewards.append(reward)
            
            self._log_generation(
                prompt, completion, reward, predicted_answer, 
                pseudo_label, p_hat, match, idx
            )
            
            pbar.set_postfix({"reward": f"{reward:.1f}", "match": match})
        
        avg_reward = sum(rewards) / len(rewards) if rewards else 0
        accuracy = sum(1 for r in rewards if r > 0) / len(rewards) if rewards else 0
        logger.info(f"📊 Batch {self.call_count}: avg_reward={avg_reward:.3f}, accuracy={accuracy:.1%}")
        
        if WANDB_AVAILABLE and wandb.run is not None:
            wandb.log({
                "executor/batch_reward": avg_reward,
                "executor/batch_accuracy": accuracy,
            })
        
        return rewards
    
    def _log_generation(self, prompt, completion, reward, predicted, pseudo_label, p_hat, match, idx):
        log_entry = {
            "batch": self.call_count,
            "idx": idx,
            "reward": reward,
            "predicted_answer": predicted,
            "pseudo_label": pseudo_label,
            "p_hat": p_hat,
            "match": match,
            "completion_preview": completion[:300] if completion else "",
        }
        self.generation_log.append(log_entry)
    
    def save_logs(self, suffix: str = ""):
        if not self.generation_log:
            return 0
        
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        jsonl_path = self.output_dir / f"executor_generations_{timestamp}{suffix}.jsonl"
        save_generations_to_jsonl(self.generation_log, str(jsonl_path), mode='w')
        
        csv_data = [
            {
                "batch": log["batch"],
                "idx": log["idx"],
                "reward": log["reward"],
                "match": log["match"],
                "predicted": log["predicted_answer"],
                "pseudo_label": log["pseudo_label"],
                "p_hat": log["p_hat"],
            }
            for log in self.generation_log
        ]
        csv_path = self.output_dir / f"executor_summary_{timestamp}{suffix}.csv"
        save_generations_to_csv(csv_data, str(csv_path), mode='w')
        
        logger.success(f"💾 Saved {len(self.generation_log)} logs")
        
        saved_count = len(self.generation_log)
        self.generation_log = []
        return saved_count


# ============================================================================
# Main Training Function
# ============================================================================

def train_executor_agent(
    model_name: str = "Qwen/Qwen3-0.6B",
    curriculum_model_path: Optional[str] = None,
    output_dir: str = "./outputs/executor",
    num_tasks: int = 200,
    k_samples: int = 4,
    delta: float = 0.25,
    num_generations: int = 4,
    max_steps: int = 40,
    learning_rate: float = 1e-6,
    per_device_batch_size: int = 2,
    gradient_accumulation_steps: int = 4,
    use_lora: bool = False,
    lora_r: int = 32,
    use_wandb: bool = True,
    wandb_project: str = "agent0-executor",
    wandb_run_name: Optional[str] = None,
    save_steps: int = 10,
    logging_steps: int = 1,
    use_adpo_scaling: bool = False,
):
    """Train the Executor Agent using GRPO."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    logger.info("=" * 60)
    logger.info("🚀 EXECUTOR AGENT TRAINING")
    logger.info("=" * 60)
    
    # Initialize W&B
    if use_wandb and WANDB_AVAILABLE:
        run_name = wandb_run_name or f"executor_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        wandb.init(
            project=wandb_project,
            name=run_name,
            config={
                "model_name": model_name,
                "curriculum_model_path": curriculum_model_path,
                "num_tasks": num_tasks,
                "k_samples": k_samples,
                "delta": delta,
                "num_generations": num_generations,
                "max_steps": max_steps,
                "learning_rate": learning_rate,
                "use_lora": use_lora,
                "use_adpo_scaling": use_adpo_scaling,
            }
        )
        logger.success(f"📊 W
